In [2]:
import numpy as np
import pandas as pd
import random as rd
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

df = pd.read_csv('All_Feature_TrainIDdataset.csv')
df = df.drop(labels=['Unnamed: 0'],axis = 1)
df

,Gender,Age,Under_30,Senior_Citizen,Married,Dependents,Number_of_Dependents,Latitude,Longitude,Satisfaction Score,...,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Total Extra Data Charges,Total Revenue,Churn Category
0,1.0,37.0,0.0,1.0,0.0,0.0,0.0,34.903052,-118.411251,1.0,...,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,3923.45,1.0
1,0.0,54.0,0.0,0.0,0.0,0.0,0.0,34.903052,-118.411251,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,35.90,1.0
2,1.0,46.0,1.0,1.0,0.0,1.0,0.0,33.721917,-118.043237,3.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2182.45,0.0
3,1.0,23.0,1.0,1.0,0.0,0.0,0.0,36.192042,-122.000887,3.0,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,10.0,705.61,1.0
4,0.0,41.0,0.0,0.0,1.0,0.0,0.0,39.672813,-120.456699,3.0,...,0.0,0.0,0.0,0.0,2.0,0.0,1.0,10.0,3075.66,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5629,1.0,27.0,1.0,1.0,1.0,0.0,0.0,36.192042,-121.396719,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,62.35,0.0
5630,0.0,50.0,0.0,0.0,0.0,0.0,0.0,37.140104,-119.657092,3.0,...,0.0,0.0,0.0,1.0,2.0,0.0,1.0,0.0,3714.50,0.0
5631,1.0,60.0,0.0,1.0,0.0,1.0,2.0,37.140104,-119.657092,4.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1396.02,0.0
5632,0.0,46.0,0.0,0.0,0.0,1.0,3.0,36.192042,-119.754941,4.0,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1699.88,0.0
5633,1.0,71.0,0.0,1.0,1.0,0.0,0.0,36.623632,-119.741322,4.0,...,0.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,899.24,0.0

In [3]:
df['Churn Category'].value_counts()

0.0    4185
1.0     654
3.0     267
2.0     233
4.0     154
5.0     141
Name: Churn Category, dtype: int64

In [4]:
#undersampling

df = shuffle(df)
df = df.sort_values(by=['Churn Category'])
df

,Gender,Age,Under_30,Senior_Citizen,Married,Dependents,Number_of_Dependents,Latitude,Longitude,Satisfaction Score,...,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Total Extra Data Charges,Total Revenue,Churn Category
1162,0.0,42.0,0.0,0.0,0.0,0.0,0.0,40.582399,-122.195512,3.0,...,1.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,9754.430000,0.0
430,0.0,46.0,1.0,0.0,0.0,0.0,0.0,36.192042,-120.877572,2.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,670.870000,0.0
4706,1.0,45.0,0.0,1.0,0.0,0.0,0.0,36.296851,-117.865469,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,3133.380000,0.0
1190,0.0,30.0,0.0,0.0,1.0,0.0,0.0,39.562239,-121.148360,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1579.090000,0.0
1708,0.0,46.0,0.0,0.0,0.0,0.0,0.0,32.825086,-117.199424,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2372.850000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,1.0,71.0,0.0,1.0,0.0,0.0,0.0,38.140719,-121.838298,3.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3044.441077,5.0
1642,1.0,43.0,0.0,1.0,0.0,1.0,2.0,33.806708,-117.020070,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,3454.450000,5.0
5273,1.0,55.0,0.0,1.0,1.0,1.0,3.0,34.167926,-119.754941,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,515.140000,5.0
2492,0.0,41.0,1.0,0.0,1.0,0.0,0.0,33.987945,-118.370442,3.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,40.0,983.910000,5.0
934,0.0,46.0,0.0,0.0,0.0,1.0,0.0,34.631362,-120.238218,2.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,118.890000,5.0

In [5]:
df0 = df.iloc[0:140,:]
df1 = df.iloc[4185:4326,:] 
df2 = df.iloc[4839:4980,:]
df3 = df.iloc[5072:5213,:]
df4 = df.iloc[5339:5480,:]
df4 = df.iloc[5493:5634,:]

In [6]:
df0 = df0.to_numpy()
df1 = df1.to_numpy()
df2 = df2.to_numpy()
df3 = df3.to_numpy()
df4 = df4.to_numpy()

df_underosp = np.vstack((df0,df1))
df_underosp = np.vstack((df_underosp,df2))
df_underosp = np.vstack((df_underosp,df3))
df_underosp = np.vstack((df_underosp,df4))

df_underosp = pd.DataFrame(df_underosp)
df_underosp

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,0.0,42.0,0.0,0.0,0.0,0.0,0.0,40.582399,-122.195512,3.0,...,1.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,9754.430000,0.0
1,0.0,46.0,1.0,0.0,0.0,0.0,0.0,36.192042,-120.877572,2.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,670.870000,0.0
2,1.0,45.0,0.0,1.0,0.0,0.0,0.0,36.296851,-117.865469,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,3133.380000,0.0
3,0.0,30.0,0.0,0.0,1.0,0.0,0.0,39.562239,-121.148360,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1579.090000,0.0
4,0.0,46.0,0.0,0.0,0.0,0.0,0.0,32.825086,-117.199424,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2372.850000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,1.0,71.0,0.0,1.0,0.0,0.0,0.0,38.140719,-121.838298,3.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3044.441077,5.0
700,1.0,43.0,0.0,1.0,0.0,1.0,2.0,33.806708,-117.020070,3.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,3454.450000,5.0
701,1.0,55.0,0.0,1.0,1.0,1.0,3.0,34.167926,-119.754941,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,515.140000,5.0
702,0.0,41.0,1.0,0.0,1.0,0.0,0.0,33.987945,-118.370442,3.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,40.0,983.910000,5.0
703,0.0,46.0,0.0,0.0,0.0,1.0,0.0,34.631362,-120.238218,2.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,118.890000,5.0

In [7]:
x = df_underosp.iloc[:,:-1]
y = df_underosp.iloc[:,-1]

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
clf = SVC(kernel='poly',degree=2,C=1,gamma='auto',decision_function_shape='ovo')
clf.fit(x_train,y_train)
y_predict = clf.predict(x_test)
print(clf.score(x_train,y_train))
print(clf.score(x_test,y_test))
print(y_predict)

In [ ]:
TestID = pd.read_csv('TestID_withFeature.csv')
TestID = TestID.drop(labels=['Unnamed: 0'],axis=1)
y_predict_testID = clf.predict(TestID)
y_predict_testID